name: Test asan cffi python issue

on: [push]

jobs:
  run-test:

    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        py:
          - cp39
          - cp310

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cffi==1.15.0
